services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"


  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"


  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - "6379:6379"


  postgres_users:
    image: postgres:16
    container_name: postgres_users
    env_file:
      - .env.docker
    environment:
      POSTGRES_USER: ${POSTGRES_USER_USERS}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_USERS}
      POSTGRES_DB: ${POSTGRES_DB_USERS}
    volumes:
      - ./user/pg_users:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always


  postgres_products:
    image: postgres:16
    container_name: postgres_products
    env_file:
      - .env.docker
    environment:
      POSTGRES_USER: ${POSTGRES_USER_PRODUCTS}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_PRODUCTS}
      POSTGRES_DB: ${POSTGRES_DB_PRODUCTS}
    volumes:
      - ./product/pg_products:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always


  postgres_orders:
    image: postgres:16
    container_name: postgres_orders
    env_file:
      - .env.docker
    environment:
      POSTGRES_USER: ${POSTGRES_USER_ORDERS}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_ORDERS}
      POSTGRES_DB: ${POSTGRES_DB_ORDERS}
    volumes:
      - ./order/pg_orders:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: always


  api_user:
    build:
      context: ./user
    container_name: api_user
    depends_on:
      - postgres_users
      - kafka
      - redis
    env_file:
      - .env.docker
    environment:
      POSTGRES_USERS_HOST: ${POSTGRES_USERS_HOST}
      POSTGRES_USERS_PORT: ${POSTGRES_USERS_PORT}
      POSTGRES_DB_USERS: ${POSTGRES_DB_USERS}
      POSTGRES_USER_USERS: ${POSTGRES_USER_USERS}
      POSTGRES_PASSWORD_USERS: ${POSTGRES_PASSWORD_USERS}

      KAFKA_BROKER: ${KAFKA_URL}
      REDIS_HOST: ${REDIS_URL}
    command: /user/.venv/bin/uvicorn main:app --host 0.0.0.0 --port ${USER_PORT}
    ports:
      - "8000:8000"
    restart: on-failure


  api_product:
    build:
      context: ./product
    container_name: api_product
    depends_on:
      - postgres_products
      - kafka
      - redis
    env_file:
      - .env.docker
    environment:
      POSTGRES_PRODUCTS_HOST: ${POSTGRES_PRODUCTS_HOST}
      POSTGRES_PRODUCTS_PORT: ${POSTGRES_PRODUCTS_PORT}
      POSTGRES_DB_PRODUCTS: ${POSTGRES_DB_PRODUCTS}
      POSTGRES_USER_PRODUCTS: ${POSTGRES_USER_PRODUCTS}
      POSTGRES_PASSWORD_PRODUCTS: ${POSTGRES_PASSWORD_PRODUCTS}

      KAFKA_BROKER: ${KAFKA_URL}
      REDIS_HOST: ${REDIS_URL}
    command: /product/.venv/bin/uvicorn main:app --host 0.0.0.0 --port ${PRODUCT_PORT}
    ports:
      - "8001:8001"
    restart: on-failure


  api_order:
    build:
      context: ./order
    container_name: api_order
    depends_on:
      - postgres_orders
      - kafka
      - redis
    env_file:
      - .env.docker
    environment:
      POSTGRES_ORDERS_HOST: ${POSTGRES_ORDERS_HOST}
      POSTGRES_ORDERS_PORT: ${POSTGRES_ORDERS_PORT}
      POSTGRES_DB_ORDERS: ${POSTGRES_DB_ORDERS}
      POSTGRES_USER_ORDERS: ${POSTGRES_USER_ORDERS}
      POSTGRES_PASSWORD_ORDERS: ${POSTGRES_PASSWORD_ORDERS}

      KAFKA_BROKER: ${KAFKA_URL}
      REDIS_HOST: ${REDIS_URL}
    command: /order/.venv/bin/uvicorn main:app --host 0.0.0.0 --port ${ORDER_PORT}
    ports:
      - "8002:8002"
    restart: on-failure
